name: Laravel CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cancel-workflow:
    runs-on: ubuntu-20.04
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    steps:
      - name: Cancel previous redundant workflows
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: dgeo_sail
          POSTGRES_USER: sail
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U sail"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, bcmath, pdo_pgsql

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Create .env file
        run: |
          cp .env.example .env
          php artisan key:generate
          sed -i 's/DB_HOST=postgres/DB_HOST=127.0.0.1/' .env # Actualizo DB_HOST para que utilice la ip del servicio

      - name: Wait for PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          until pg_isready -h 127.0.0.1 -p 5432 -U sail; do
            echo "Waiting for PostgreSQL...";
            sleep 5;
          done

      - name: Run migrations and seed
        run: php artisan migrate --no-interaction --force --seed

      - name: Save composer cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Save .env file
        run: |
          echo .env > ${{ secrets.ENV }}

  test:
    runs-on: ubuntu-20.04

    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Restore composer cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, bcmath, pdo_pgsql

      - name: Restore .env file
        run: |
          echo ${{ secrets.ENV }} > .env

      - name: Run tests
        run: php artisan test
